FROM python:3.10-slim
WORKDIR /sacoMeasure
ADD . /sacoMeasure
RUN python3 -m pip install -r requirements.txt

#docker run -it --rm -v /Users/xlinx/IdeaProjects/saco-measure/pyApp:/sacoMeasure soco-measure:v1 bash
# CMD python sacoMain.py
#docker build -t soco-measure:v1 .
#docker run -it --rm soco-measure:v1 bash